[[headers]]
  for = "/cachetest*"
  [headers.values]
    Edge-Control = "600"
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://api.kvk.nl/api/v2/ https://tagmanager.google.com ; manifest-src 'self'"
