[[headers]]
  for = "/cachetest*"
  [headers.values]
    Cache-Control = "s-maxage=300, max-age=150, public"
    Edge-Control = "max-age=900"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"
