[[headers]]
  for = "/cachetest*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src *; media-src media1.com media2.com; script-src userscripts.example.com"
    Cache-Control = "s-maxage=0, max-age=150, public"
    Edge-Cache-Tag = "purgeme"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"
