export function onClientRequest (request) {
  try {
    // ...
    // Code that might fail
    // ...
  } catch(error) {
    logger.log (error.toString())
    // ...
    // Error handling logic
    // ...
  }
}
